#!/bin/bash
set -euo pipefail

# ══════════════════════════════════════════════════════════════
# Open Brain — Init Script
# Applies migrations and seeds the owner brain + API key.
# Idempotent — safe to re-run on every container start.
#
# Secrets are generated by start.sh BEFORE docker compose up.
# This script receives them as environment variables.
# ══════════════════════════════════════════════════════════════

MIGRATIONS_DIR="/migrations"
OWNER_BRAIN_ID="00000000-0000-4000-a000-000000000001"

# ── Wait for Postgres ────────────────────────────────────────
wait_for_db() {
  echo "Waiting for Postgres..."
  local retries=30
  while [ $retries -gt 0 ]; do
    if pg_isready -h db -U postgres -q 2>/dev/null; then
      echo "Postgres is ready."
      return 0
    fi
    retries=$((retries - 1))
    sleep 1
  done
  echo "ERROR: Postgres did not become ready in 30s"
  exit 1
}

# ── Apply migrations ─────────────────────────────────────────
apply_migrations() {
  echo "Applying migrations..."
  local count=0

  for sql_file in "$MIGRATIONS_DIR"/*.sql; do
    [ -f "$sql_file" ] || continue
    local filename
    filename=$(basename "$sql_file")
    if PGPASSWORD="$POSTGRES_PASSWORD" psql -h db -U postgres -d postgres -f "$sql_file" -v ON_ERROR_STOP=1 > /dev/null; then
      count=$((count + 1))
    else
      echo "  WARN: $filename had errors (may already be applied)"
      count=$((count + 1))
    fi
  done

  echo "Applied $count migrations."
}

# ── Seed owner brain API key ─────────────────────────────────
seed_api_key() {
  local existing
  existing=$(PGPASSWORD="$POSTGRES_PASSWORD" psql -h db -U postgres -d postgres -tAc \
    "SELECT COUNT(*) FROM brain_api_keys WHERE brain_id = '$OWNER_BRAIN_ID' AND revoked_at IS NULL;" 2>/dev/null || echo "0")

  if [ "$existing" != "0" ] && [ -n "$existing" ]; then
    echo "API key already exists for owner brain. Skipping seed."
    return 0
  fi

  # SHA-256 hash the MCP_ACCESS_KEY (must match auth.ts hashKey())
  local key_hash
  key_hash=$(echo -n "$MCP_ACCESS_KEY" | sha256sum | awk '{print $1}')
  local key_prefix="${MCP_ACCESS_KEY:0:8}"

  PGPASSWORD="$POSTGRES_PASSWORD" psql -h db -U postgres -d postgres -c \
    "INSERT INTO brain_api_keys (brain_id, key_hash, key_prefix, label)
     VALUES ('$OWNER_BRAIN_ID', '$key_hash', '$key_prefix', 'docker-init')
     ON CONFLICT DO NOTHING;"

  echo "Owner API key seeded."
}

# ── Notify PostgREST to reload schema ────────────────────────
notify_postgrest() {
  PGPASSWORD="$POSTGRES_PASSWORD" psql -h db -U postgres -d postgres -c \
    "NOTIFY pgrst, 'reload schema';" > /dev/null 2>&1 || true
}

# ── Print connection info ────────────────────────────────────
print_banner() {
  echo ""
  echo "══════════════════════════════════════════════════════════════"
  echo " Open Brain initialized successfully!"
  echo ""
  echo " Your MCP access key: $MCP_ACCESS_KEY"
  echo ""
  echo " Connect your MCP client:"
  echo "   URL: http://localhost:80/functions/v1/open-brain-mcp"
  echo "   Header: x-brain-key: $MCP_ACCESS_KEY"
  echo "══════════════════════════════════════════════════════════════"
  echo ""
}

# ── Main ─────────────────────────────────────────────────────
main() {
  echo "Open Brain init starting..."

  wait_for_db
  apply_migrations
  seed_api_key
  notify_postgrest
  print_banner

  echo "Init complete."
}

main
